FROM registry.ci.openshift.org/openshift/release:golang-1.18
ENV GO111MODULE=on
ENV GOFLAGS=""

RUN yum install -y docker docker-compose && \
    yum clean all
COPY --from=quay.io/app-sre/golangci-lint:v1.46.0 /usr/bin/golangci-lint /usr/bin/golangci-lint
RUN go install golang.org/x/tools/cmd/goimports@v0.1.0
RUN go install github.com/onsi/ginkgo/ginkgo@v1.16.1
RUN go install github.com/golang/mock/mockgen@v1.6.0
RUN go install github.com/vektra/mockery/v2@v2.9.6
RUN go install gotest.tools/gotestsum@v1.6.3
RUN go install github.com/axw/gocov/gocov@latest
RUN go install github.com/AlekSi/gocov-xml@latest
